[package]
name = "rewriter"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.10"

[dev-dependencies]
assert_cmd = "2.0"

[features]
check-offsets = []
check-rewrites = []
__check-proc-macro2-spans = []

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
missing-errors-doc = "allow"
missing-panics-doc = "allow"
# smoelius: Revisit allowing `clippy::must-use-candidate`.
must-use-candidate = "allow"

[lints.rust.unexpected_cfgs]
level = "deny"
check-cfg = ["cfg(dylint_lib, values(any()))"]
