[package]
name = "rewriter"
version = "0.1.0"
edition = "2021"

[dependencies]
tempfile = "3.10"

[features]
check-offsets = []
check-rewrites = []
check-spans = []

[lints.rust.unexpected_cfgs]
level = "deny"
check-cfg = ["cfg(dylint_lib, values(any()))"]
